nav:
  - Dealer (PaaS): dealer
  - Subdealer (SubPaaS): subpaas
  - Account: account.md
  - User: user
  - Tracker: tracker.md
  - Equipment: equipment.md
  - Plan: tariff.md
  - Gateways: gateways.md
  - Timezone: timezone.md
  - Order: order.md
