title: Field service management
nav:
  - Creating and assigning tasks: manage-tasks.md
  - Optimizing routes: optimize-routes.md
  - Creating forms for tasks: create-forms.md
  - Chane task statuses: change-task-statuses.md